---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-nodejs
  template:
    metadata:
      labels:
        app: guestbook-nodejs
    spec:
      containers:
      - name: guestbook-nodejs
        image: peterhack/guestbook-nodejs:latest
        env:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-nodejs
  labels:
    app: guestbook-nodejs
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
    # the port that this service should serve on
  - port: 3000
